language: node_js
node_js: "12"

script:
  - npm test
  - npm run build PUBLIC_URL=https://sydbal.github.io/modular-synthesizer/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master